### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/optimize#89]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with optimize. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable optimize on @Sourcegraph by going to https://sourcegraph.com/github.com/gonum/optimize and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by kortschak** [comment]
I tried enabling that, but it wasn't able to detect the primary language and then gave a 505 and then a 404. Will try again later.

\cc @shurcooL

**Comment by shurcooL** [comment]
That's strange. Even GitHub detects it as 100% Go repo. @sqs, is this a known issue?

**Comment by sqs** [comment]
It might be stale. The 404/500 would be a different issue, though. Can you try again? I'll look into it more tomorrow. Sorry for the issues.

**Comment by kortschak** [comment]
Tried again - no good. I try in the morning tomorrow. Thanks.

**Comment by sqs** [comment]
I believe I fixed the issue. Apparently the optimize repo was deleted and recreated at some point, and Sourcegraph incorrectly had the old repo. Would you mind giving it one more try? Thanks :smile:

**Comment by kortschak** [comment]
Thanks for that. It now correctly detects a language and shows the enable button, but I'm still getting the 500.

**Comment by kortschak** [comment]
@sqs OK done and working. The 500 was a result of noscript and cookie blocking at my end. Maybe a warning in that situation could be considered. Thanks for your help.

**Comment by sqs** [comment]
Glad it finally worked, and thanks for reporting those issues. We'll look into them and get them fixed.

**Comment by kortschak** [comment]
@vladimir-ch This might be something to consider for gonum more generally. After some time using this (presumably for code review), would you be prepared to write up experiences to gonum-dev with a view to adopting more generally?

**Comment by vladimir-ch** [comment]
@kortschak Sure

**Comment by vladimir-ch** [comment]
@kortschak At first glance the UI is not as polished as GitHub, but that will surely change with time. However, I could not test it fully yet, sourcegraph has some issues building optimize and so the code is not interactive and there are no cross-references. I reported the issues.
